bozplanner/urls.py
"""Global URL configuration from the root, mostly to route to the apps."""
from django.conf.urls import url, include
from django.contrib import admin

import members.urls
import meetings.urls
import help.urls
from bozplanner import views
from bozplanner.settings import HAVE_DJANGOSAML2

urlpatterns = [
    url(r'^$', views.index, name=''),
    url(r'^admin/', admin.site.urls),
    url(r'^members/', include(members.urls)),
    url(r'^meetings/', include(meetings.urls)),
    url(r'^help/', include(help.urls)),
]

if HAVE_DJANGOSAML2:
    urlpatterns += [
        url(r'^saml2/', include('djangosaml2.urls')),
    ]

help/urls.py
from django.conf.urls import url

from help import views

app_name = "help"

urlpatterns = [
    url(r'^$', views.HelpView.as_view(), name="help"),
]

meetings/models.py
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.db import models
from django.core.urlresolvers import reverse
from datetime import datetime, timedelta
import icalendar

from meetings.managers import MeetingManager


class Meeting(models.Model):
    """A meeting planned by a planner"""
    objects = MeetingManager()

    place = models.CharField(max_length=255, verbose_name=_("place"))
    begin_time = models.DateTimeField(verbose_name=_("begin date & time"))
    end_time = models.DateTimeField(verbose_name=_("end date & time"))
    secretary = models.ForeignKey("members.Person", related_name="secretary", blank=True, null=True, verbose_name=_("secretary"))
    organization = models.ForeignKey("members.Organization", verbose_name=_("organization"))

    @property
    def is_soon(self):
        td = self.begin_time - datetime.now()
        return td <= timedelta(days=10)

    def as_icalendar_event(self):
        """Returns a copy of this meeting as an iCalendar event
        If a secretary is set, the secretary is added as an attendee."""

        event = icalendar.Event()
        event.add("summary", str(self))
        event.add("dtstart", self.begin_time)
        event.add("dtend", self.end_time)

        if self.secretary:
            secretary = icalendar.vCalAddress("MAILTO:{}".format(self.secretary.email))
            secretary.params["cn"] = self.secretary.get_full_name()
            # Required participant, refer to https://www.ietf.org/rfc/rfc2445.txt
            secretary.params["ROLE"] = "REQ-PARTICIPANT"
            event.add("attendee", secretary, encode=0)

        return event

    def clean(self):
        super(Meeting, self).clean()

        if self.begin_time > self.end_time:
            raise ValidationError(_('End of a meeting cannot be before the start of a meeting.'))

    def __str__(self):
        return _("OLC meeting of {}").format(self.organization)

    class Meta:
        permissions = [
            ("list_meetings", "Can list meetings"),
            ("list_meetings_organization", "Can list meetings of her organization"),
            ("list_meetings_all", "Can list all meetings"),
            ("view_organization", "Can view meetings from own organization"),
            ("view_all", "Can view all meetings"),
            ("view_secretaries", "Can view names of secretaries"),
        ]
        verbose_name = "Meeting"


class Minutes(models.Model):
    """Minutes corresponding to a meeting"""
    meeting = models.ForeignKey("Meeting", related_name='minutes', verbose_name=_("meeting"))
    file = models.FileField(verbose_name=_("file"))
    original_name = models.TextField(verbose_name=_("original name"))
    date = models.DateTimeField(verbose_name=_("date"))

    class Meta:
        verbose_name_plural = "minutes"
        permissions = [
            ("approve", "Can approve minutes"),
        ]

members/models.py
from django.contrib.auth.models import User, Permission, Group, AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext_lazy as _


class Person(AbstractUser):
    """Any user that can log in to BOZPlanner"""
    organizations = models.ManyToManyField("Organization", verbose_name=_("organizations"), blank=True)
    calendar_token = models.CharField(max_length=64, verbose_name=_("calendar token"), editable=False, null=True)
    first_login = models.BooleanField(default=True, verbose_name=_("first login"))

    @property
    def is_admin(self):
        return self.groups.filter(name="Administrator").exists()

    @property
    def is_planner(self):
        return self.groups.filter(name="Planner").exists()

    @property
    def is_secretary(self):
        return self.groups.filter(name="Secretary").exists()

    @property
    def is_user_manager(self):
        return self.groups.filter(name="User Manager").exists()

    @property
    def full_email(self):
        return '{} {} <{}>'.format(self.first_name, self.last_name, self.email)

    @property
    def all_organizations(self):
        result = set()

        for organization in self.organizations.all():
            result |= organization.all_organizations

        return list(result)

    def save(self, *args, **kwargs):
        if self.calendar_token is None:
            self.calendar_token = get_random_string(64, "0123456789abcdef")

        super(Person, self).save(*args, **kwargs)

    @staticmethod
    def validate_username(value):
        error = ValidationError(_('%(value)s is not a valid student number or employee number'),
            params={'value': value})

        if len(value) != 8:
            raise error

        if value[0] not in ['m', 's']:
            raise error

        if any(c not in "0123456789" for c in value[1:8]):
            raise error

    class Meta:
        verbose_name = "person"
        permissions = [
            ("change_groups", "Can change user groups"),
            ("list_persons", "Can view persons"),
        ]

    def __str__(self):
        return self.get_full_name()

Person._meta.get_field('username').help_text = _('The student number or employee number of the user, for example s1234567 or m1234567')
Person._meta.get_field('username').validators.append(Person.validate_username)
Person._meta.get_field('groups').help_text = ''
Person._meta.get_field('email').required = True
Person._meta.get_field('email').verbose_name = _('E-mailadres')


class Organization(models.Model):
    """An organization for which OLC meetings can be planned in BOZPlanner"""
    name = models.CharField(max_length=255, verbose_name=_("name"))
    parent_organization = models.ForeignKey("Organization", null=True, blank=True,
        verbose_name=_("parent organization"),
        help_text=_("The organization to which this organization belongs. For example, Technical Computer Science"
            " might belong to an organization called EWI."  ))

    @property
    def all_organizations(self):
        todo = {self}
        done = {self}

        while todo:
            org = todo.pop()

            for child in Organization.objects.filter(parent_organization=org):
                if child not in done:
                    todo.add(child)
                    done.add(child)

        return done

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "organization"
        permissions = [
            ("list_organizations", "Can list organizations"),
        ]

class Preferences(models.Model):
    person = models.OneToOneField("Person")
    overview = models.ManyToManyField(Organization, blank=True, related_name='pref_overview',
        verbose_name=_("overview"),
        help_text=_("You can use this to indicate of which organizations you would like to receive a weekly overview."))
    reminder = models.ManyToManyField(Organization, blank=True, related_name='pref_reminder',
        verbose_name=_("reminder"),
        help_text=_("You can use this to indicate of which organizations you would like to receive a reminder "
                    "whenever no secretary has been found 10 days in advance of a meeting."))

    calendar_secretary = models.BooleanField(default=True,
        verbose_name=_("Include meetings in your calendar of which you are the secretary"))
    calendar_organization = models.BooleanField(default=False,
        verbose_name=_("Include meetings in your calendar which belong to your organizations"))
    overview_secretary = models.ManyToManyField(Organization, verbose_name=_("overview secretary"), blank=True,
        related_name='student_pref_overview',
        help_text=_("You can use this to indicate of which organizations you would like to receive a weekly overview "
                    "of meetings that do not yet have a secretary."))
    confirmation_secretary = models.BooleanField(default=False,
        verbose_name=_("Receive confirmation mail when adding yourself to a meeting"),
        help_text=_("You can use this to indicate whether you would like to receive a confirmation mail whenever "
                    "you subscribe to or unsubscribe from a meeting."))

    zoom_in = models.BooleanField(default=False, verbose_name=_("Always zoom in the page"))

    class Meta:
        verbose_name_plural = 'Preferences'
        verbose_name = 'Preferences'

    def __str__(self):
        return self._meta.verbose_name + ' for ' + self.person.__str__()


@receiver(post_save, sender=Person)
def create_preferences(sender, instance, created, **kwargs):
     if created:
         Preferences.objects.create(person=instance)

help/views.py
from django.views.generic import TemplateView


class HelpView(TemplateView):
    template_name = "help/help.html"

help/templates/help/help.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block menu %}
    {% include 'menu.html' with active='help' %}
{% endblock %}

{% block content %}
    <h1>{% trans 'Help' %}</h1>
    <hr>
    <div id="questions" class="panel-group" role ="tablist" aria-multiselectable="true">
        <!-- You may see information on scheduling meeting when you are allowed to create them (Admin and Planner) -->
        {% if perms.meetings.add_meeting %}
            <div class ="panel panel-default">
                <div id="schedule-heading" class="panel-heading" role="tab">
                    <h2 class="panel-title">
                        <a class="collapsed btn-block" role="button" data-toggle="collapse" data-parent="#questions"
                           href="#schedule-question" aria-expanded="false" aria-controls="schedule-question">
                            <i class="caret"></i> {% trans 'Scheduling a meeting' %}
                        </a>
                    </h2>
                </div>
                <div id="schedule-question" class="panel-collapse collapse " style ="height: 0" aria-expanded="false"
                   role="tabpanel" aria-labelledby="schedule-heading">
                    <div class="panel-body" style="text-align: justify;">{% blocktrans %}
                       <p>In order to schedule a meeting, you should navigate in the menu to "Meetings" and click on the add button on top of the page. You should then fill in the location of the meeting (e.g. RA-5148), at what time the meeting starts (in the following format: dd/mm/yyyy hh:mm), the datetimepicker can help to fill in this field, then you should fill in at what time the meeting will end (This work exactly the same as the previous field). Next, the organization of the OLC meeting should be filled in (e.g. BMS). Finally click on the save button to save the meeting.</p>
                    {% endblocktrans %}</div>
                </div>
             </div>
        {% endif %}

        <!-- you may see information on the users overview when you are allowed to add persons or be a planner (Admin, Planner and User Manager) -->
        {% if perms.members.add_person or perms.meetings.add_meeting %}
            <div class ="panel panel-default">
                <div id="users-heading" class="panel-heading" role="tab">
                    <h2 class="panel-title">
                        <a class="collapsed btn-block" role="button" data-toggle="collapse" data-parent="#questions"
                           href="#users-question" aria-expanded="false" aria-controls="users-question">
                            <i class="caret"></i> {% trans 'Users information' %}
                        </a>
                    </h2>
                </div>
                <div id="users-question" class="panel-collapse collapse " style ="height: 0" aria-expanded="false"
                   role="tabpanel" aria-labelledby="users-heading">
                    <div class="panel-body" STYLE="text-align: justify;">{% blocktrans %}
                        <p>You can find all users of the system in the menu named "Users". This menu serves multiple purposes, firstly you can thus find all users of the system, thus students, BOZ employees and persons associated to an OLC. Secondly, an account can be created by means of the add button (found in the header of the page). Thirdly, data about the users' data can be changed when requested or even a user can be deleted from the list.</p>

                        <h4>How do I add a user?</h4>
                        <p>In order to add a user, you should as previously mentioned click on the add button on top of the "Users" page. Then you should fill in the name, email and to which organization the user is associated to. Afterwards, the person can be added by submitting the form. The person for whom you filled in the data can now access the system.</p>

                        <h4>How do I change the data of a user?</h4>
                        <p>The data of a user can be changed by clicking on the change button in the list associated to the user. Then, the data of the user pops up enabling you to make changes to it. Afterwards, the data should be submitted.</p>

                        <h4>How do I delete a user?</h4>
                        <p>A user can be deleted by clicking on the delete button in the list associated to the user. Then, you will be asked whether you are certain of deleting the user. Afterwards, click on the deactivate button to permanently deactivate the user.</p>
                    {% endblocktrans %}</div>
                </div>
            </div>
        {% endif %}

        <!-- you may see information on the organizations list when you may see this page (User Managers and Admin) -->
        {% if perms.members.list_organizations %}
            <div class ="panel panel-default">
                <div id="organizations-heading" class="panel-heading" role="tab">
                    <h2 class="panel-title">
                        <a class="collapsed btn-block" role="button" data-toggle="collapse" data-parent="#questions"
                           href="#organizations-question" aria-expanded="false" aria-controls="organizations-question">
                            <i class="caret"></i> {% trans 'Organizations information' %}
                        </a>
                    </h2>
                </div>
                <div id="organizations-question" class="panel-collapse collapse " style ="height: 0"
                   aria-expanded="false" role="tabpanel" aria-labelledby="organizations-heading">
                    <div class="panel-body" style="text-align: justify;">{% blocktrans %}
                        <p>You can find all the organizations in the system in the menu named "Organizations". The organizations can be accessed, added, changed and deleted in similar steps as with users. Please refer to the previous answered question.</p>
                    {% endblocktrans %}</div>
                </div>
            </div>
        {% endif %}

        <!-- You may see information on scheduled meeting when you are allowed to see them (Admin, Planners and Secretaries)-->
        {% if perms.meetings.list_meetings %}
            <div class ="panel panel-default">
                <div id="meetings-heading" class="panel-heading" role="tab">
                    <h2 class="panel-title">
                        <a class="collapsed btn-block" role="button" data-toggle="collapse" data-parent="#questions"
                           href="#meetings-question" aria-expanded="false" aria-controls="meetings-question">
                            <i class="caret"></i> {% trans 'Scheduled meetings' %}
                        </a>
                    </h2>
                </div>
                <div id="meetings-question" class="panel-collapse collapse " style ="height: 0" aria-expanded="false"
                   role="tabpanel" aria-labelledby="meetings-heading">
                    <div class="panel-body" style="text-align: justify;">{% blocktrans %}
                        <p>Scheduled meetings can be found in the menu called "Meetings", this menu lists the meetings and it indicates whether someone is assigned to the meeting to take the minutes. Furthermore, with the button in the header, a meeting can be scheduled instantly .</p>
                    {% endblocktrans %}</div>
                </div>
            </div>
            <div class ="panel panel-default">
                <div id="minutes-heading" class="panel-heading" role="tab">
                    <h2 class="panel-title">
                        <a class="collapsed btn-block" role="button" data-toggle="collapse" data-parent="#questions"
                           href="#minutes-question" aria-expanded="false" aria-controls="minutes-question">
                            <i class="caret"></i> {% trans 'Minutes' %}
                        </a>
                    </h2>
                </div>
                <div id="minutes-question" class="panel-collapse collapse " style ="height: 0" aria-expanded="false"
                   role="tabpanel" aria-labelledby="minutes-heading">
                    <div class="panel-body" style="text-align: justify;">{% blocktrans %}
                        <p>In order to download minutes from meetings that took place in the past, you should navigate to the menu named "Minutes". In this menu, the past meetings are listed. When minutes are uploaded by the student, a download button can be found on the right hand side in the list. It could be the case that a student has uploaded multiple versions of the minutes. In that case, you are able to chose which version you would like to download.</p>
                    {% endblocktrans %}</div>
                </div>
            </div>
        {% endif %}

        <!-- You may see information on the settings when you are a user of the system (Thus everybody) -->
        <div class ="panel panel-default">
            <div id="settings-heading" class="panel-heading" role="tab">
                <h2 class="panel-title">
                    <a class="collapsed btn-block" role="button" data-toggle="collapse" data-parent="#questions"
                       href="#settings-question" aria-expanded="false" aria-controls="settings-question">
                        <i class="caret"></i> {% trans 'Personal settings' %}
                    </a>
                </h2>
            </div>
            <div id="settings-question" class="panel-collapse collapse " style ="height: 0" aria-expanded="false"
               role="tabpanel" aria-labelledby="settings-heading">
                <div class="panel-body" style="text-align: justify;">{% blocktrans %}
                    <p>You can access your personal settings by clicking on the right hand side on the tab with your name. Then, a dropdown menu opens including a tab for your settings. You can change your preferred settings by enabling the different options (notification mails and reminders of your planned meetings) and you can change your own personal data.'</p>
                {% endblocktrans %}</div>
            </div>
        </div>
    </div>

    <h1>{% trans 'Manual' %}</h1>
    <hr>
    {% static 'manual.pdf' as static_manual_url %}
    {% blocktrans %}
        The complete manual can be downloaded <em><a href="{{ static_manual_url }}">here</a></em>.
    {% endblocktrans %}

{%  endblock %}