bozplanner/urls.py
"""Global URL configuration from the root, mostly to route to the apps."""
from django.conf.urls import url, include
from django.contrib import admin

import members.urls
import meetings.urls
import help.urls
from bozplanner import views
from bozplanner.settings import HAVE_DJANGOSAML2

urlpatterns = [
    url(r'^$', views.index, name=''),
    url(r'^admin/', admin.site.urls),
    url(r'^members/', include(members.urls)),
    url(r'^meetings/', include(meetings.urls)),
    url(r'^help/', include(help.urls)),
]

if HAVE_DJANGOSAML2:
    urlpatterns += [
        url(r'^saml2/', include('djangosaml2.urls')),
    ]

help/urls.py
from django.conf.urls import url

from help import views

app_name = "help"

urlpatterns = [
    url(r'^$', views.HelpView.as_view(), name="help"),
]

members/urls.py
from django.conf.urls import url

from members import views
from members.views import *

app_name = "members"

urlpatterns = [
    url(r'^logout/$', views.logout, name="logout"),

    url(r'^person/$', ListPersonView.as_view(), name="list_person"),
    url(r'^person/create/$', AddPersonView.as_view(), name="add_person"),
    url(r'^person/(?P<pk>[0-9]+)/delete/$', DeletePersonView.as_view(), name="delete_person"),

    url(r'^organization/$', ListOrganizationView.as_view(), name="list_organization"),
    url(r'^organization/create/$', AddOrganizationView.as_view(), name="add_organization"),
    url(r'^organization/(?P<pk>[0-9]+)/delete/', DeleteOrganizationView.as_view(), name="delete_organization"),
    url(r'^organization/emails/(?P<organizations>[0-9]+(,[0-9]+)*)', EmailOrganizationView.as_view(), name="email_organization"),

    url(r'^preferences/$', PreferencesView.as_view(), name="preferences"),
]

members/models.py
from django.contrib.auth.models import User, Permission, Group, AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext_lazy as _


class Person(AbstractUser):
    """Any user that can log in to BOZPlanner"""
    organizations = models.ManyToManyField("Organization", verbose_name=_("organizations"), blank=True)
    calendar_token = models.CharField(max_length=64, verbose_name=_("calendar token"), editable=False, null=True)
    first_login = models.BooleanField(default=True, verbose_name=_("first login"))

    @property
    def is_admin(self):
        return self.groups.filter(name="Administrator").exists()

    @property
    def is_planner(self):
        return self.groups.filter(name="Planner").exists()

    @property
    def is_secretary(self):
        return self.groups.filter(name="Secretary").exists()

    @property
    def is_user_manager(self):
        return self.groups.filter(name="User Manager").exists()

    @property
    def full_email(self):
        return '{} {} <{}>'.format(self.first_name, self.last_name, self.email)

    @property
    def all_organizations(self):
        result = set()

        for organization in self.organizations.all():
            result |= organization.all_organizations

        return list(result)

    def save(self, *args, **kwargs):
        if self.calendar_token is None:
            self.calendar_token = get_random_string(64, "0123456789abcdef")

        super(Person, self).save(*args, **kwargs)

    @staticmethod
    def validate_username(value):
        error = ValidationError(_('%(value)s is not a valid student number or employee number'),
            params={'value': value})

        if len(value) != 8:
            raise error

        if value[0] not in ['m', 's']:
            raise error

        if any(c not in "0123456789" for c in value[1:8]):
            raise error

    class Meta:
        verbose_name = "person"
        permissions = [
            ("change_groups", "Can change user groups"),
            ("list_persons", "Can view persons"),
        ]

    def __str__(self):
        return self.get_full_name()

Person._meta.get_field('username').help_text = _('The student number or employee number of the user, for example s1234567 or m1234567')
Person._meta.get_field('username').validators.append(Person.validate_username)
Person._meta.get_field('groups').help_text = ''
Person._meta.get_field('email').required = True
Person._meta.get_field('email').verbose_name = _('E-mailadres')


class Organization(models.Model):
    """An organization for which OLC meetings can be planned in BOZPlanner"""
    name = models.CharField(max_length=255, verbose_name=_("name"))
    parent_organization = models.ForeignKey("Organization", null=True, blank=True,
        verbose_name=_("parent organization"),
        help_text=_("The organization to which this organization belongs. For example, Technical Computer Science"
            " might belong to an organization called EWI."  ))

    @property
    def all_organizations(self):
        todo = {self}
        done = {self}

        while todo:
            org = todo.pop()

            for child in Organization.objects.filter(parent_organization=org):
                if child not in done:
                    todo.add(child)
                    done.add(child)

        return done

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "organization"
        permissions = [
            ("list_organizations", "Can list organizations"),
        ]

class Preferences(models.Model):
    person = models.OneToOneField("Person")
    overview = models.ManyToManyField(Organization, blank=True, related_name='pref_overview',
        verbose_name=_("overview"),
        help_text=_("You can use this to indicate of which organizations you would like to receive a weekly overview."))
    reminder = models.ManyToManyField(Organization, blank=True, related_name='pref_reminder',
        verbose_name=_("reminder"),
        help_text=_("You can use this to indicate of which organizations you would like to receive a reminder "
                    "whenever no secretary has been found 10 days in advance of a meeting."))

    calendar_secretary = models.BooleanField(default=True,
        verbose_name=_("Include meetings in your calendar of which you are the secretary"))
    calendar_organization = models.BooleanField(default=False,
        verbose_name=_("Include meetings in your calendar which belong to your organizations"))
    overview_secretary = models.ManyToManyField(Organization, verbose_name=_("overview secretary"), blank=True,
        related_name='student_pref_overview',
        help_text=_("You can use this to indicate of which organizations you would like to receive a weekly overview "
                    "of meetings that do not yet have a secretary."))
    confirmation_secretary = models.BooleanField(default=False,
        verbose_name=_("Receive confirmation mail when adding yourself to a meeting"),
        help_text=_("You can use this to indicate whether you would like to receive a confirmation mail whenever "
                    "you subscribe to or unsubscribe from a meeting."))

    zoom_in = models.BooleanField(default=False, verbose_name=_("Always zoom in the page"))

    class Meta:
        verbose_name_plural = 'Preferences'
        verbose_name = 'Preferences'

    def __str__(self):
        return self._meta.verbose_name + ' for ' + self.person.__str__()


@receiver(post_save, sender=Person)
def create_preferences(sender, instance, created, **kwargs):
     if created:
         Preferences.objects.create(person=instance)

members/forms.py
from django.forms import models

from members.models import Organization, Person, Preferences


class OrganizationForm(models.ModelForm):
    class Meta:
        model = Organization
        fields = ['name', 'parent_organization']


class PersonForm(models.ModelForm):
    class Meta:
        model = Person
        fields = ['username', 'first_name', 'last_name', 'email', 'groups', 'organizations']


class PreferencesForm(models.ModelForm):
    def __init__(self, *args, request, **kwargs):
        self.request = request
        super(PreferencesForm, self).__init__(*args, **kwargs)
        self.fields['overview_secretary'].queryset = Organization.objects.filter(
            pk__in=map(lambda org: org.pk, self.request.user.all_organizations))

    def clean(self):
        cleaned_data = super(PreferencesForm, self).clean()

        organizations = self.request.user.all_organizations

        if any(group not in organizations for group in cleaned_data.get('overview_secretary') or []):
            raise PermissionError

    class Meta:
        model = Preferences
        fields = [
            'overview',
            'reminder',
            'calendar_secretary',
            'calendar_organization',
            'zoom_in',
            'overview_secretary',
            'confirmation_secretary'
        ]

members/views.py
from urllib.parse import urlencode
from django.contrib.auth import login
from django.core.urlresolvers import reverse_lazy
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import auth
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, View

from bozplanner.local import WEBCAL_BASE
from bozplanner.settings import HAVE_DJANGOSAML2, LOGOUT_REDIRECT_URL
from bozplanner.views import EditModalListView
from members.auth import permission_required
from members.forms import OrganizationForm, PersonForm, PreferencesForm
from members.models import Person, Organization, Preferences


@permission_required("members.list_persons")
class ListPersonView(EditModalListView):
    model = Person
    form = PersonForm
    edit_permission = "members.change_person"
    success_url = reverse_lazy("members:list_person")
    template_name = "person/list.html"

    def get_context_data(self):
        object_list = Person.objects.filter(is_active=True)
        return locals()


@permission_required("members.add_person")
class AddPersonView(CreateView):
    template_name = "person/form.html"
    model = Person
    success_url = reverse_lazy("members:list_person")
    fields = [
        "username",
        "first_name",
        "last_name",
        "email",
        "groups",
        "organizations",
    ]


@permission_required("members.delete_person")
class DeletePersonView(View):
    def post(self, request, pk):
        object = get_object_or_404(Person, pk=pk)
        object.is_active = False
        object.save()
        return redirect("members:list_person")


@permission_required("members.list_organizations")
class ListOrganizationView(EditModalListView):
    model = Organization
    form = OrganizationForm
    edit_permission = "members.change_organization"
    success_url = reverse_lazy("members:list_organization")
    template_name = "organization/list.html"

    def get_context_data(self):
        object_list = Organization.objects.all()
        return locals()


@permission_required("members.add_organization")
class AddOrganizationView(CreateView):
    template_name = "organization/form.html"
    model = Organization
    success_url = reverse_lazy("members:list_organization")
    fields = [
        "name",
        "parent_organization",
    ]


@permission_required("members.delete_organization")
class DeleteOrganizationView(DeleteView):
    template_name = "organization/delete.html"
    model = Organization
    success_url = reverse_lazy("members:list_organization")


@permission_required("members.list_organizations")
class EmailOrganizationView(View):
    def get(self, request, organizations):
        # Verified by URL pattern
        org_ids = map(int, organizations.split(","))
        organizations = set()

        for org_id in org_ids:
            organization = get_object_or_404(Organization, pk=org_id)
            organizations = organizations | organization.all_organizations

        persons = Person.objects.filter(organizations__in=organizations, is_active=True)
        return JsonResponse({"result": list(map(lambda person: person.full_email, persons))})


def logout(request):
    if HAVE_DJANGOSAML2:
        import djangosaml2.views
        result = djangosaml2.views.logout(request)
        auth.logout(request)
        return result
    else:
        auth.logout(request)
        return redirect(LOGOUT_REDIRECT_URL)


class PreferencesView(UpdateView):
    template_name = "settings.html"
    form_class = PreferencesForm
    success_url = reverse_lazy("members:preferences")

    def get_object(self, queryset=None):
       return self.request.user.preferences

    def get_form_kwargs(self):
        args = super(PreferencesView, self).get_form_kwargs()
        args['request'] = self.request
        return args

    def get_context_data(self, **kwargs):
        context = super(PreferencesView, self).get_context_data()
        context['first_login'] = self.request.user.first_login
        context['webcal_url'] = 'webcal://{}/meetings/calendar/{}/{}'.format(
            WEBCAL_BASE, self.request.user.id, self.request.user.calendar_token)
        google_args = {'cid': 'http://{}/meetings/calendar/{}/{}'.format(
            WEBCAL_BASE, self.request.user.id, self.request.user.calendar_token
        )}
        context['google_url'] = 'http://www.google.com/calendar/render?' + urlencode(google_args)

        if self.request.user.first_login:
            self.request.user.first_login = False
            self.request.user.save()

        return context

members/templates/organization/form.html
{% extends 'base-organizations.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-2"><!-- Dummy --></div>
        <div class="col-md-8">
            {% if object %}
                <h1>{% blocktrans %}Edit organization {{ object }}{% endblocktrans %}</h1>
            {% else %}
                <h1>{% trans 'Create organization' %}</h1>
            {% endif %}
            <hr>

            <div>
                <form method="post">
                    {% csrf_token %}
                    {{ form|fancy_form }}
                    <hr>
                    <a href="{% url 'members:list_organization' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
                    <input type="submit" value="{% trans 'Submit' %}" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

members/templates/organization/list.html
{% extends 'base-organizations.html' %}

{% block content %}
    <h1>
        {% trans 'Organizations' %}
        {% if perms.members.add_organization %}
            <a href="{% url 'members:add_organization' %}" class="btn btn-default">
                <i class="glyphicon glyphicon-plus"></i>
            </a>
        {% endif %}
        <hr>
    </h1>

    <table class="table table-hover data-table" data-order='[[0, "asc"]]' data-select="multi">
        <thead>
            <tr>
                <th>{% trans 'Name' %}</th>
                <th>{% trans 'Parent organization' %}</th>
                <th class="btn-cell no-sort"><!-- Buttons --></th>
            </tr>
        </thead>

        <tbody>
        {% for organization in object_list %}
            <tr data-id="{{ organization.pk }}">
                <td>{{ organization }}</td>
                <td>
                    {% if organization.parent_organization != None %}
                        {{ organization.parent_organization }}
                    {% else %}
                        <em><small>{% trans 'None' %}</small></em>
                    {% endif %}
                </td>
                <td class="btn-cell">
                    <div>
                        {% if perms.members.change_organization %}
                            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#editModal-{{ organization.pk }}">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </button>
                        {% endif %}
                        &nbsp;
                        {% if perms.members.delete_organization %}
                            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#deleteModal-{{ organization.pk }}">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </button>
                        {% endif %}
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <!-- Pop-up windows for editing an organization -->
    {% for organization in object_list %}
        <div id="editModal-{{ organization.pk }}" class="modal fade" role="form" {% if edit != None %}data-backdrop="static"{% endif %}>
            <div class="modal-dialog">
                <div class="modal-content">
                    <form method="post" action="{% url 'members:list_organization' %}">
                        <div class="modal-header">
                            {% if edit == organization.pk %}
                                <a href="{% url 'members:list_organization' %}" type="button" class="close">&times;</a>
                            {% else %}
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            {% endif %}
                            <h4 class="modal-title">{% trans 'Edit organization' %}</h4>
                        </div>

                        <div class="modal-body">
                            <input type="hidden" name="edit" value="{{ organization.pk }}">
                            {% csrf_token %}
                            {{ organization.form|fancy_form }}
                        </div>
                        <div class="modal-footer">
                            {% if edit == organization.pk %}
                                <a href="{% url 'members:list_organization' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
                            {% else %}
                                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Cancel'%}</button>
                            {% endif %}
                            <input class="btn btn-primary" type="submit" value="{% trans 'Submit' %}">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endfor %}

    {% if edit %}
        <script type="text/javascript">
            $(function() {
                $('#editModal-{{ edit }}').modal().show();
            })
        </script>
    {% endif %}

    <!-- Pop-up windows for deleting an organization -->
    {% for organization in object_list %}
        <div id="deleteModal-{{ organization.pk }}" class="modal fade" role="form">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form method="post" action="{% url 'members:delete_organization' organization.pk %}">
                        {% csrf_token %}
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">{% trans 'Delete organization' %}</h4>
                        </div>
                        <div class="modal-body">
                            {% blocktrans %}
                                Are you sure you want to permanently delete the organization {{ organization }}? This will <em>delete all suborganizations</em> as well.
                            {% endblocktrans %}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Cancel' %}</button>
                            <input class="btn btn-danger" type="submit" value={% trans 'Delete' %}>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endfor %}

    <div id="email-modal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">{% trans 'Copy email addresses' %}</h4>
                </div>
                <div class="modal-body">
                    <div class="input-group">
                        <input id="email-input" type="text" class="form-control" onclick="this.select()" autofocus>
                        <span class="input-group-btn">
                            <button id="email-copy-button" class="btn btn-default copy-button">
                                <i class="glyphicon glyphicon-copy"></i> {% trans 'Copy' %}
                            </button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(function() {
            $('table').on('init.dt', function() {
                $('table').on('select.dt deselect.dt', function() {
                    $('.select-info .select-item:nth-child(2)').empty().append(
                        $('<button>').addClass('btn').addClass('btn-default').text({{ 'Email organizations'|jstrans }}).click(function() {
                            var query = $('tr.selected').map(function() {
                                return $(this).attr('data-id');
                            }).get().join(',');

                            $.get('emails/' + query, function(data) {
                                var value = data.result.join(',');
                                $('#email-input').val(value);
                                $('#email-copy-button').attr('data-clipboard-text', value);
                                $('#email-modal').modal().show();
                            });
                        })
                    );
                });
            });
        });
    </script>
{% endblock %}