bozplanner/urls.py
"""Global URL configuration from the root, mostly to route to the apps."""
from django.conf.urls import url, include
from django.contrib import admin

import members.urls
import meetings.urls
import help.urls
from bozplanner import views
from bozplanner.settings import HAVE_DJANGOSAML2

urlpatterns = [
    url(r'^$', views.index, name=''),
    url(r'^admin/', admin.site.urls),
    url(r'^members/', include(members.urls)),
    url(r'^meetings/', include(meetings.urls)),
    url(r'^help/', include(help.urls)),
]

if HAVE_DJANGOSAML2:
    urlpatterns += [
        url(r'^saml2/', include('djangosaml2.urls')),
    ]

help/urls.py
from django.conf.urls import url

from help import views

app_name = "help"

urlpatterns = [
    url(r'^$', views.HelpView.as_view(), name="help"),
]

meetings/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from meetings.views import *

app_name = 'meetings'

urlpatterns = [
    url(r'^$', ListMeetingView.as_view(), name="list_meeting"),
    url(r'^(?P<pk>[0-9]+)/toggle/$', ToggleMeetingView.as_view(), name="toggle_meeting"),
    url(r'^minutes/$', ListMinutesView.as_view(), name='list_minutes'),
    url(r'^minutes/upload/$', UploadMinutesView.as_view(), name='upload_minutes'),
    url(r'^add/$', AddMeetingView.as_view(), name="add_meeting"),
    url(r'^(?P<pk>[0-9]+)/delete/$', DeleteMeetingView.as_view(), name='delete_meeting'),
    url(r'^minutes/(?P<pk>[0-9]+)/download/$', DownloadMinutesView.as_view(), name='download_minutes'),
    url(r'^minutes/(?P<pk>[0-9]+)/delete/$', DeleteMinutesView.as_view(), name='delete_minutes'),
    url(r'^calendar/(?P<pk>[0-9]+)/(?P<token>[0-9a-f]{64})/$', CalendarMeetingView.as_view(), name='calendar_meeting'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.conf.urls import url

from members import views
from members.views import *

app_name = "members"

urlpatterns = [
    url(r'^logout/$', views.logout, name="logout"),

    url(r'^person/$', ListPersonView.as_view(), name="list_person"),
    url(r'^person/create/$', AddPersonView.as_view(), name="add_person"),
    url(r'^person/(?P<pk>[0-9]+)/delete/$', DeletePersonView.as_view(), name="delete_person"),

    url(r'^organization/$', ListOrganizationView.as_view(), name="list_organization"),
    url(r'^organization/create/$', AddOrganizationView.as_view(), name="add_organization"),
    url(r'^organization/(?P<pk>[0-9]+)/delete/', DeleteOrganizationView.as_view(), name="delete_organization"),
    url(r'^organization/emails/(?P<organizations>[0-9]+(,[0-9]+)*)', EmailOrganizationView.as_view(), name="email_organization"),

    url(r'^preferences/$', PreferencesView.as_view(), name="preferences"),
]

bozplanner/views.py
from abc import ABCMeta, abstractmethod

from django.forms import ModelForm
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import View

from bozplanner.settings import LOGIN_URL


class EditModalListView(View):
    __metaclass__ = ABCMeta
    form = ModelForm
    template_name = None
    model = None
    success_url = None
    edit_permission = None

    @abstractmethod
    def get_context_data(self):
        pass

    def _context(self):
        """Add forms to the subclass-provided object_list"""
        ctx = self.get_context_data()

        for obj in ctx["object_list"]:
            obj.form = type(self).form(instance=obj, auto_id='%s_' + str(obj.pk))

        return ctx

    def get(self, request):
        return render(request, type(self).template_name, self._context())

    def post(self, request):
        if "edit" not in request.POST:
            return self.get(request)

        if not request.user.has_perm(type(self).edit_permission):
            raise PermissionError

        instance = get_object_or_404(type(self).model, pk=int(request.POST["edit"]))

        form = type(self).form(request.POST, instance=instance)

        if form.is_valid():
            form.save()
            return redirect(type(self).success_url or instance.get_absolute_url())
        else:
            ctx = self._context()

            # Insert the user values in the correct form
            for obj in ctx["object_list"]:
                if obj == instance:
                    obj.form = form

            # Tell the template to open this modal immediately
            ctx["edit"] = instance.pk

            return render(request, type(self).template_name, ctx)


def index(request):
    """Redirects the user to the login page when not authenticated.
    When the user logs in for the first time, the redirect is to the preferences page instead of the home page."""
    if request.user.is_authenticated():
        if request.user.first_login:
            return redirect('members:preferences')
        else:
            return redirect('meetings:list_meeting')
    else:
        return redirect(LOGIN_URL)

bozplanner/templates/base.html
{% load staticfiles %}
{% get_current_language as LANGUAGE_CODE %}

<!doctype html>
<html>
    <head>
        <title>{% trans 'BOZPlanner' %}</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap-toggle.css' %}">
        <link rel="stylesheet" href="{% static 'datatables.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap-multiselect.css' %}">
        <link rel="stylesheet" href={%  static 'datetimpicker.min.css' %}>
        <link rel="stylesheet" href="{% static 'pnotify.custom.min.css' %}">

        <link rel="stylesheet" href="{% static 'style.css' %}">

        <script src="{% static 'jquery.min.js' %}"></script>
        <script src="{% static 'jquery.cookie.js' %}"></script>
        <script src="{% static 'jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'moment-with-locales.min.js' %}"></script>
        <script src="{% static 'ZeroClipboard.min.js' %}"></script>

        <script src="{% static 'bootstrap.min.js' %}"></script>
        <script src="{% static 'datatables.min.js' %}"></script>
        <script src="{% static 'bootstrap-toggle.min.js' %}"></script>
        <script src="{% static 'bootstrap-multiselect.js' %}"></script>
        <script src="{% static 'pnotify.custom.min.js' %}"></script>
        <script src="{% static 'bootstrap.datetime.min.js' %}"></script>

        <script type="text/javascript">
            $(function() {
                $('.data-table').each(function() {
                    var table = $(this);
                    table.DataTable({
                        language: {
                            url: '{% static 'datatables-i18n' %}/{{ LANGUAGE_CODE }}.json'
                        },
                        responsive: true,
                        order: JSON.parse(table.attr('data-order')),
                        ordering: true,
                        aoColumnDefs: [{
                            bSortable: false,
                            aTargets: ["no-sort"]
                        }],
                        select: table.attr('data-select')
                    });
                });
            });

            $(function() {
                var oldBegin;

               $('input[name=begin_time]').focus(function() {
                   var self = $(this);
                   oldBegin = self.closest('.date').data('DateTimePicker').date();
                   console.log(oldBegin);
               }).closest('.date').on('dp.change', function() {
                   var self = $(this);

                   var begin = self.data('DateTimePicker').date();
                   var endInput = self.closest('form').find('input[name=end_time]');
                   var end = endInput.closest('.date').data('DateTimePicker').date();

                   if(begin !== null) {
                       if(end === null) {
                           endInput.val(begin.format('DD-MM-Y HH:mm'));
                       } else {
                           endInput.val(begin.clone().add(end.diff(oldBegin)).format('DD-MM-Y HH:mm'));
                       }
                   }
               });
            });

            $(function() {
                var client = new ZeroClipboard($('.copy-button'));
            });
        </script>
    </head>

    <body {% if request.user.preferences.zoom_in %}class="zoom-in"{% endif %}>
        {% block menu %}{% include 'menu.html' with active='' %}{% endblock %}

        <div class="container" id="content">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

bozplanner/templates/confirmation_mail_student_html.html
{% extends "mail_base.html" %}
{% block content %}
Hello,<br><br>

You have {% if added %}{% else %}de{% endif %}registered for the meeting on {{ meeting.begin_time|date:"d-m-Y H:i" }}. <br><br>

Kind regards,<br>
BOZPlanner
{% endblock %}

bozplanner/templates/confirmation_mail_student_plain.html
Hello,

You have {% if added %}{% else %}de{% endif %}registered for the meeting on {{ meeting.begin_time|date:"d-m-Y H:i" }}.

Kind regards,
BOZPlanner

bozplanner/templates/form-field-help.html
{% if field.help_text %}
    <i class="glyphicon glyphicon-question-sign" title="{{ field.help_text }}"></i>
{% endif %}

bozplanner/templates/form-field.html
{% get_current_language as LANGUAGE_CODE %}

<div class="form-group">
    {% if field|field_class_is:"TextInput" %}
        <label for="{{ field.id_for_label }}">{{ field.label }} {% include 'form-field-help.html' %}</label>
        {% include 'form-field-errors.html' %}
        <input type="text" id="{{ field.id_for_label }}" name="{{ field.name }}" value="{{ field.value|default:"" }}" class="form-control">

    {% elif field|field_class_is:"EmailInput" %}
        <label for="{{ field.id_for_label }}">{{ field.label }} {% include 'form-field-help.html' %}</label>
        {% include 'form-field-errors.html' %}
        <input type="text" id="{{ field.id_for_label }}" name="{{ field.name }}" value="{{ field.value|default:"" }}" class="form-control" placeholder="example@utwente.nl">

    {% elif field|field_class_is:"CheckboxInput" %}
        <label for="{{ field.id_for_label }}">
            <input type="checkbox" id="{{ field.id_for_label }}" name="{{ field.name }}" {% if field.value %}checked="checked"{% endif %}>
            {{ field.label }}
            {% include 'form-field-help.html' %}
        </label>
        {% include 'form-field-errors.html' %}

    {% elif field|field_class_is:"SelectMultiple" %}
        <label for="{{ field.id_for_label }}">{{ field.label }} {% include 'form-field-help.html' %}</label>
        {% include 'form-field-errors.html' %}
        <div>{{ field }}</div>
        <script type="text/javascript">
            $("#{{ field.id_for_label }}").multiselect({
                disabledText: {{ ''|jstrans }},
                allSelectedText: {{ 'All selected'|jstrans }},
                nonSelectedText: {{ 'None selected'|jstrans }},
                nSelectedText: {{ 'selected'|jstrans }},
                delimiterText: {{ ', '|jstrans }},
                selectAllText: {{ 'Select all'|jstrans }},
                filterPlaceholder: {{ 'Search'|jstrans }}
            });
        </script>

    {% elif field|field_class_is:"Select" %}
        <label for="{{ field.id_for_label }}">{{ field.label }} {% include 'form-field-help.html' %}</label>
        {% include 'form-field-errors.html' %}
        <div>{{ field }}</div>
        <script type="text/javascript">
            $("#{{ field.id_for_label }}").multiselect({
                enableFiltering: true,
                disabledText: {{ ''|jstrans }},
                allSelectedText: {{ 'All selected'|jstrans }},
                nonSelectedText: {{ 'None selected'|jstrans }},
                nSelectedText: {{ 'selected'|jstrans }},
                delimiterText: {{ ', '|jstrans }},
                selectAllText: {{ 'Select all'|jstrans }},
                filterPlaceholder: {{ 'Search'|jstrans }}
            });
        </script>

    {% elif field|field_class_is:"DateTimeInput" %}
        <label for="{{ field.id_for_label }}">{{ field.label }} {% include 'form-field-help.html' %}</label>
        {% include 'form-field-errors.html' %}
        <div class='input-group date' id='{{ field.id_for_label }}'>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
            <input type='text' class="form-control" name="{{ field.name }}" placeholder="{% now "d-m-Y" %} 00:00"
                   value="{% if field.value|is_str %}{{ field.value }}{% else %}{{ field.value|date:"d-m-Y H:i" }}{% endif %}">
        </div>


        <script type="text/javascript">
            $('#{{ field.id_for_label }}').datetimepicker({
                format: 'DD-MM-Y HH:mm',
                locale: '{{ LANGUAGE_CODE }}',
                sideBySide: true,
                allowInputToggle: true,
                toolbarPlacement: 'bottom',
                showClose: true,
                icons: {
                    close: 'glyphicon glyphicon-ok'
                }
            });
        </script>

    {% else %}
        <script type="text/javascript">alert("Unknown field class {{ field|field_class }}, please add it to bozplanner/templates/form-field.html.");</script>
        {% include 'form-field-errors.html' %}
    {% endif %}
</div>

bozplanner/templates/form.html
{% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        <i class="glyphicon glyphicon-alert"></i>
        {{ error }}
    </div>
{% endfor %}

{% for field in form.hidden_fields %}
    {{ field }}
{% endfor %}

{% for field in form.visible_fields %}
    {{ field|fancy_form_field }}
{% endfor %}

bozplanner/templates/mail_base.html
<html>
<body>

<table align="center" cellspacing="0" cellpadding="0" style="font-family: Verdana, sans-serif; width: 600px; margin-top:20px; background-color: white; border: 1px solid #CCC; font-size: 14px;">
    <tr style="background-color: #E92F8C; height: 6px; font-size: 1px;" >
        <td>
            &nbsp;
        </td>
    </tr>

    <tr>
        <td>
            <div style="background-image: url('https://blackboard.utwente.nl/branding/_1_1/Header.png'); background-color: #111; background-position: center; height: 100px; width: 100%;" ></div>
        </td>
    </tr>

    <tr>
        <td style="padding:40px 10px 40px 10px;">
            {% block content %}
            {% endblock %}
        </td>
    </tr>

    <tr style="background-color: #E92F8C;">
       <td style="padding:4px;">
           <div style="margin-left: 10px; font-size: 12px;">
            <b>BOZPlanner</b> <a href="http://www.bozplanner.nl" style="color: white;">bozplanner.nl</a>
           </div>
       </td>
    </tr>
</table>

</body>
</html>

bozplanner/templates/menu.html
<nav class="navbar navbar-default navbar-static-top">
    {% if active == '' %}
        <script type="text/javascript">alert('Please define the active variable for this template.');</script>
    {% endif %}

    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{%  url 'meetings:list_meeting' %}">{% trans 'BOZPlanner' %}</a>
        </div>

        <ul class="nav navbar-nav">
            {% if perms.meetings.list_meetings %}
                <li class="{% if active == 'meetings' %}active{% endif %}">
                    <a href="{% url 'meetings:list_meeting' %}">
                        {% trans 'Meetings' %}
                    </a>
                </li>
                <li class="{% if active == 'minutes' %}active{% endif %}">
                    <a href="{% url 'meetings:list_minutes' %}">
                        {% trans 'Minutes' %}
                    </a>
                </li>
            {% endif %}

            {% if perms.members.list_persons %}
                <li class="{% if active == 'users' %}active{% endif %}">
                    <a href="{% url 'members:list_person' %}">
                        {%  trans 'Users' %}
                    </a>
                </li>
            {% endif %}

            {% if perms.members.list_organizations %}
                <li class="{% if active == 'organizations' %}active{% endif %}">
                    <a href="{% url 'members:list_organization' %}">
                        {% trans 'Organizations' %}
                    </a>
                </li>
            {% endif %}
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li class="{% if active == 'help' %}active{% endif %}">
                <a href="{% url 'help:help' %}">
                    <span class="glyphicon glyphicon-question-sign"></span> {% trans 'Help' %}
                </a>
            </li>

            <li class="dropdown">
                <a class="dropdown-toggle" type="button" data-toggle="dropdown" href="#">
                    {{ request.user.get_full_name }} <span class="caret"></span>
                </a>

                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'members:preferences' %}">
                            <span class="glyphicon glyphicon-cog"></span> {% trans 'Preferences' %}
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'members:logout' %}">
                            <span class="glyphicon glyphicon-off"></span> {% trans 'Log out' %}
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

bozplanner/templates/overview_mail_html.html
{% extends "mail_base.html" %}
{% block content %}
Hello,<br><br>

This week the following meeting{% if meetings|length == 1 %}{% else %}s{% endif %} take{% if meetings|length == 1 %}s{% else %}{% endif %} place of {{ organization }}: <br>
    <ul>
    {% for meeting in meetings %}
        {% if meeting.secretary == None %}
            <li>{{ meeting.begin_time|date:"d-m-Y H:i" }}, no secretary</li>
        {% else %}
            <li>{{ meeting.begin_time|date:"d-m-Y H:i" }}</li>
        {% endif %}
    {% endfor %}
    </ul>
Kind regards,<br>
BOZPlanner
{% endblock %}

bozplanner/templates/overview_mail_plain.html
Hello,

This week the following meeting{% if meetings|length == 1 %}{% else %}s{% endif %} take{% if meetings|length == 1 %}s{% else %}{% endif %} place of {{ organization }}:

{% for meeting in meetings %}
    - {{ meeting.begin_time|date:"d-m-Y H:i" }}{% if meeting.secretary == None %}, no secretary{% endif %}{% endfor %}

Kind regards,<br>
BOZPlanner

bozplanner/templates/overview_mail_student_html.html
{% extends "mail_base.html" %}
{% block content %}
Hello,<br><br>

This week the following meeting{% if meetings|length == 1 %}{% else %}s{% endif %} take{% if meetings|length == 1 %}s{% else %}{% endif %} place of {{ organization }} that do{% if meetings|length == 1 %}es{% else %}{% endif %} not yet have a secretary: <br>
    <ul>
    {% for meeting in meetings %}
        <li>{{ meeting.begin_time|date:"d-m-Y H:i" }}</li>
    {% endfor %}
    </ul>
Kind regards,<br>
BOZPlanner
{% endblock %}

bozplanner/templates/overview_mail_student_plain.html
Hello,

This week the following meeting{% if meetings|length == 1 %}{% else %}s{% endif %} take{% if meetings|length == 1 %}s{% else %}{% endif %} place of {{ organization }} that do{% if meetings|length == 1 %}es{% else %}{% endif %} not yet have a secretary:
{% for meeting in meetings %}
    - {{ meeting.begin_time|date:"d-m-Y H:i" }}{% endfor %}

Kind regards,
BOZPlanner

bozplanner/templates/reminder_mail_html.html
{% extends "mail_base.html" %}
{% block content %}
Hello,<br><br>
{% if meetings|length == 1 %}
The meeting of {{ meetings.0.begin_time|date:"d-m-Y H:i" }} of {{ organization }} does not have a secretary yet.<br><br>
{% else %}
    The following meetings of {{ organization }} do not have a secretary yet: <br>
    <ul>
    {% for meeting in meetings %}
        <li>{{ meeting.begin_time|date:"d-m-Y H:i" }}</li>
    {% endfor %}
    </ul>
{% endif %}
Kind regards,<br>
BOZPlanner
{% endblock %}

bozplanner/templates/reminder_mail_plain.html
Hello,
{% if meetings|length == 1 %}
The meeting of {{ meetings.0.begin_time|date:"d-m-Y H:i" }} of {{ organization }} does not have a secretary yet.
{% else %}
    The following meetings of {{ organization }} do not have a secretary yet:
    {% for meeting in meetings %}
    - {{ meeting.begin_time|date:"d-m-Y H:i" }}{% endfor %}{% endif %}
Kind regards,
BOZPlanner