bozplanner/urls.py
"""Global URL configuration from the root, mostly to route to the apps."""
from django.conf.urls import url, include
from django.contrib import admin

import members.urls
import meetings.urls
import help.urls
from bozplanner import views
from bozplanner.settings import HAVE_DJANGOSAML2

urlpatterns = [
    url(r'^$', views.index, name=''),
    url(r'^admin/', admin.site.urls),
    url(r'^members/', include(members.urls)),
    url(r'^meetings/', include(meetings.urls)),
    url(r'^help/', include(help.urls)),
]

if HAVE_DJANGOSAML2:
    urlpatterns += [
        url(r'^saml2/', include('djangosaml2.urls')),
    ]

help/urls.py
from django.conf.urls import url

from help import views

app_name = "help"

urlpatterns = [
    url(r'^$', views.HelpView.as_view(), name="help"),
]

meetings/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from meetings.views import *

app_name = 'meetings'

urlpatterns = [
    url(r'^$', ListMeetingView.as_view(), name="list_meeting"),
    url(r'^(?P<pk>[0-9]+)/toggle/$', ToggleMeetingView.as_view(), name="toggle_meeting"),
    url(r'^minutes/$', ListMinutesView.as_view(), name='list_minutes'),
    url(r'^minutes/upload/$', UploadMinutesView.as_view(), name='upload_minutes'),
    url(r'^add/$', AddMeetingView.as_view(), name="add_meeting"),
    url(r'^(?P<pk>[0-9]+)/delete/$', DeleteMeetingView.as_view(), name='delete_meeting'),
    url(r'^minutes/(?P<pk>[0-9]+)/download/$', DownloadMinutesView.as_view(), name='download_minutes'),
    url(r'^minutes/(?P<pk>[0-9]+)/delete/$', DeleteMinutesView.as_view(), name='delete_minutes'),
    url(r'^calendar/(?P<pk>[0-9]+)/(?P<token>[0-9a-f]{64})/$', CalendarMeetingView.as_view(), name='calendar_meeting'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meetings/models.py
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.db import models
from django.core.urlresolvers import reverse
from datetime import datetime, timedelta
import icalendar

from meetings.managers import MeetingManager


class Meeting(models.Model):
    """A meeting planned by a planner"""
    objects = MeetingManager()

    place = models.CharField(max_length=255, verbose_name=_("place"))
    begin_time = models.DateTimeField(verbose_name=_("begin date & time"))
    end_time = models.DateTimeField(verbose_name=_("end date & time"))
    secretary = models.ForeignKey("members.Person", related_name="secretary", blank=True, null=True, verbose_name=_("secretary"))
    organization = models.ForeignKey("members.Organization", verbose_name=_("organization"))

    @property
    def is_soon(self):
        td = self.begin_time - datetime.now()
        return td <= timedelta(days=10)

    def as_icalendar_event(self):
        """Returns a copy of this meeting as an iCalendar event
        If a secretary is set, the secretary is added as an attendee."""

        event = icalendar.Event()
        event.add("summary", str(self))
        event.add("dtstart", self.begin_time)
        event.add("dtend", self.end_time)

        if self.secretary:
            secretary = icalendar.vCalAddress("MAILTO:{}".format(self.secretary.email))
            secretary.params["cn"] = self.secretary.get_full_name()
            # Required participant, refer to https://www.ietf.org/rfc/rfc2445.txt
            secretary.params["ROLE"] = "REQ-PARTICIPANT"
            event.add("attendee", secretary, encode=0)

        return event

    def clean(self):
        super(Meeting, self).clean()

        if self.begin_time > self.end_time:
            raise ValidationError(_('End of a meeting cannot be before the start of a meeting.'))

    def __str__(self):
        return _("OLC meeting of {}").format(self.organization)

    class Meta:
        permissions = [
            ("list_meetings", "Can list meetings"),
            ("list_meetings_organization", "Can list meetings of her organization"),
            ("list_meetings_all", "Can list all meetings"),
            ("view_organization", "Can view meetings from own organization"),
            ("view_all", "Can view all meetings"),
            ("view_secretaries", "Can view names of secretaries"),
        ]
        verbose_name = "Meeting"


class Minutes(models.Model):
    """Minutes corresponding to a meeting"""
    meeting = models.ForeignKey("Meeting", related_name='minutes', verbose_name=_("meeting"))
    file = models.FileField(verbose_name=_("file"))
    original_name = models.TextField(verbose_name=_("original name"))
    date = models.DateTimeField(verbose_name=_("date"))

    class Meta:
        verbose_name_plural = "minutes"
        permissions = [
            ("approve", "Can approve minutes"),
        ]

meetings/forms.py
from django import forms

from meetings.models import Meeting
from members.models import Person


class MeetingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MeetingForm, self).__init__(*args, **kwargs)
        self.fields['secretary'].queryset = Person.objects.filter(is_active=True)

    class Meta:
        fields = ['organization', 'secretary', 'begin_time', 'end_time', 'place']
        model = Meeting

meetings/views.py
import mimetypes
import urllib
import datetime
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.shortcuts import get_object_or_404, render
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import redirect
from django.views.generic import CreateView, UpdateView, DeleteView, View, TemplateView
from django.http import HttpResponse, JsonResponse
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives

from bozplanner.views import EditModalListView
from meetings.forms import MeetingForm
from meetings.models import Meeting, Minutes
from members.auth import permission_required, login_required
from members.models import Person


@permission_required('meetings.list_meetings')
class ListMeetingView(EditModalListView):
    model = Meeting
    form = MeetingForm
    edit_permission = "meetings.change_meeting"
    success_url = reverse_lazy("meetings:list_meeting")
    template_name = 'meetings/list.html'

    def get_context_data(self):
        now = datetime.datetime.now()

        # First condition: You should be able to see upcoming meetings where you are the secretary
        q = Q(end_time__gt=now, secretary=self.request.user)

        # If the user may only see meetings from his/her own (sub-)organization(s), put all upcoming
        # meetings of this organization in context
        if self.request.user.has_perm('meetings.list_meetings_organization'):
            # Second condition: Only meetings from own (sub-)organization(s) should be shown
            q |= Q(organization__in=self.request.user.all_organizations, end_time__gt=now)

        if self.request.user.has_perm('meetings.list_meetings_all'):
            # Should be able to see all meetings
            q |= Q(end_time__gt=now)

        object_list = list(filter_meetings(q))

        return locals()


@permission_required("meetings.add_meeting")
class AddMeetingView(CreateView):
    model = Meeting
    fields = ['organization', 'begin_time', 'end_time', 'place']
    success_url = reverse_lazy('meetings:list_meeting')
    template_name = 'meetings/form.html'


class ToggleMeetingView(View):
    def post(self, request, pk):
        meeting = get_object_or_404(Meeting, pk=pk)

        if meeting.secretary is None:
            meeting.secretary = request.user
            meeting.save()
            send_confirmation_email(meeting, request.user, added=True)
        elif meeting.secretary == request.user:
            if meeting.is_soon:
                return JsonResponse(
                    {"error": True, "error_message": _("You cannot unsubscribe from this meeting anymore")})
            else:
                meeting.secretary = None
                meeting.save()
                send_confirmation_email(meeting, request.user, added=False)
        else:
            return JsonResponse({"error": True, "error_message": _("Someone has already claimed this meeting.")})

        return JsonResponse(
            {"error": False, "secretary": meeting.secretary.get_full_name() if meeting.secretary else None})


@permission_required('meetings.delete_meeting')
class DeleteMeetingView(DeleteView):
    model = Meeting
    success_url = reverse_lazy('meetings:list_meeting')


@permission_required('meetings.list_meetings')
class ListMinutesView(TemplateView):
    model = Meeting
    template_name = 'minutes/list.html'

    def get_context_data(self, **kwargs):
        now = datetime.datetime.now()

        # Should be able to see all meetings (with minutes) for which you were secretary
        q = Q(begin_time__lt=now, secretary=self.request.user)

        # Should be able to see all meetings (with minutes) from own organizations
        # if self.request.user.has_perm('meetings.list_meetings_organization'):
        #     q |= Q(organization__in=self.request.user.all_organizations, begin_time__lt=now)

        # Should be able to see all meetings (with minutes)
        if self.request.user.has_perm('meetings.list_meetings_all'):
            q |= Q(begin_time__lt=now)

        object_list = filter_meetings(q).prefetch_related('minutes')

        return locals()


@login_required
class UploadMinutesView(View):
    model = Minutes
    succes_url = reverse_lazy('meetings')
    template_name = 'meetings/upload_minutes.html'

    def post(self, request, *args, **kwargs):
        form = request.POST
        meeting = get_object_or_404(Meeting, pk=form.get('meeting'))

        if not (meeting.secretary == request.user or request.user.has_perm('meetings.add_minutes')):
            raise PermissionError

        file = request.FILES['minutes']
        date = datetime.datetime.now()
        original_name = file.name
        minutes = Minutes.objects.create(file=file, meeting=meeting, original_name=original_name, date=date)
        minutes.save()

        return redirect('meetings:list_minutes')


@permission_required('meetings.list_meetings')
class DownloadMinutesView(View):
    def get(self, request, pk):
        file = get_object_or_404(Minutes, pk=pk)
        response = HttpResponse(open(file.file.path, 'rb').read(),
            content_type=mimetypes.guess_type(file.original_name)[0] or 'application/octet-stream')
        response['Content-Disposition'] = 'attachment; filename=%s' % urllib.parse.quote(file.original_name)
        return response


@permission_required("meetings.delete_minutes")
class DeleteMinutesView(View):
    def post(self, request, pk):
        minutes = get_object_or_404(Minutes, pk=pk)
        minutes.delete()
        return redirect("meetings:list_minutes")


class CalendarMeetingView(View):
    def get(self, request, pk, token):
        person = get_object_or_404(Person, pk=pk)

        if person.calendar_token != token:
            raise PermissionError

        meeting_filter = ~Q()

        if person.preferences.calendar_secretary:
            meeting_filter |= Q(secretary=person)

        if person.preferences.calendar_organization:
            meeting_filter |= Q(organization__in=person.all_organizations)

        calendar = Meeting.objects.filter(meeting_filter).as_icalendar()
        return HttpResponse(calendar.to_ical(), content_type="text/calendar")


def filter_meetings(perms):
    return Meeting.objects.filter(perms)


def filter_minutes(perms):
    return Minutes.objects.filter(perms)


def send_confirmation_email(meeting, person, added=True):
    mail_context = {'meeting': meeting, 'added': added}
    subject = '[BOZPlanner] Confirmation meeting ' + meeting.begin_time.strftime('%Y-%m-%d %H:%M')
    text_content = get_template('confirmation_mail_student_plain.html').render(context=mail_context)
    html_content = get_template('confirmation_mail_student_html.html').render(context=mail_context)
    from_email = 'bozplanner@utwente.nl'
    to = [person.email]

    mail = EmailMultiAlternatives(subject, text_content, from_email, to)
    mail.attach_alternative(html_content, "text/html")
    mail.send()

meetings/templates/minutes/list.html
{% extends "base-minutes.html" %}

{% block content %}
    <h1>{% trans 'Minutes' %}</h1>
    <hr>

    <!-- List of meetings with minutes -->
    <div class="table">
       <table class="table table-hover data-table" data-order='[[1, "desc"]]'>
            <thead>
                <tr>
                    <th>{% trans 'Subject' %}</th>
                    <th>{% trans 'Date & Time' %}</th>
                    <th>{% trans 'Location' %}</th>
                    <th>{% trans 'Secretary' %}</th>
                    <th class="btn-cell no-sort">{%  trans 'Upload&nbsp;-&nbsp;Options' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for meeting in object_list %}
                    <tr>
                        <td>{{ meeting.organization }}</td>
                        <td data-order="{{ meeting.begin_time|date:"YmdHi" }}">{{ meeting.begin_time }}</td>
                        <td>{{ meeting.place }}</td>
                        {% if meeting.secretary != None %}
                            <td>
                                {{ meeting.secretary }}
                            </td>
                        {% else %}
                            <td>
                                <em><small>{% trans 'None' %}</small></em>
                            </td>
                        {% endif %}

                        <td class="btn-cell"><div>
                            <!-- Upload minutes form -->
                            {% if meeting.secretary == user or perms.meetings.add_minutes %}
                                <form method="post" action="{% url 'meetings:upload_minutes' %}" class="upload-form" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <input type="hidden" name="meeting" value="{{ meeting.pk }}">
                                    <input type="file" name="minutes" style="display: none">
                                    <button type="button" class="btn btn-default">
                                        <span class="glyphicon glyphicon-open" aria-hidden="true"></span>
                                    </button>
                                </form>
                            {% endif %}

                            &nbsp;

                            {% if meeting.minutes.all|length > 0 %}
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        {% trans 'Minutes' %} <span class="caret"></span>
                                    </button>

                                    <ul class="dropdown-menu pull-right">
                                        {% for minutes in meeting.minutes.all %}
                                            <li style="vertical-align: middle;">
                                                <a onclick="window.location='{% url 'meetings:download_minutes' minutes.pk %}'" style="cursor: pointer; display: flex">
                                                    <span style="margin-right: 8px">{{ minutes.original_name }}</span>
                                                    <em style="flex-grow: 1"><small>{{ minutes.date }}</small></em>
                                                    <span class="btn btn-default btn-sm dropdown-button">
                                                        <i class="glyphicon glyphicon-save"></i>
                                                    </span>
                                                    {% if perms.meetings.delete_minutes %}
                                                        <span onclick="event.preventDefault(); event.stopPropagation(); event.stopImmediatePropagation(); $('#deleteModal-{{ minutes.pk }}').modal('show')"
                                                           href="#" class="btn btn-danger btn-sm dropdown-button"
                                                           data-toggle="modal" data-target="deleteModal-{{ minutes.pk }}"
                                                           style="margin-left: 3px">
                                                            <i class="glyphicon glyphicon-remove"></i>
                                                        </span>
                                                    {% endif %}
                                                </a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endif %}
                        </div></td>
                    </tr>
                {% endfor %}
           </tbody>
       </table>
    </div>

    <!-- Modals to delete minutes -->
    {% for meeting in object_list %}
        {% for minutes in meeting.minutes.all %}
            <div id="deleteModal-{{ minutes.pk }}" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <form method="post" action="{% url 'meetings:delete_minutes' minutes.pk %}">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">{% trans 'Delete minutes' %}</h4>
                            </div>
                            <div class="modal-body">
                                {% csrf_token %}
                                {% blocktrans with name=minutes.original_name date=minutes.date%}
                                    Are you sure you want to remove the file {{ name }} uploaded at {{ date }}?
                                {% endblocktrans %}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Cancel' %}</button>
                                <input class="btn btn-danger" type="submit" value="{% trans 'Delete' %}">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endfor %}

    <script type="text/javascript">
        $(function() {
            $('.upload-form').each(function() {
                var form = $(this);

                form.find('button').click(function() {
                    form.find('input[type=file]').click();
                });

                form.find('input[type=file]').change(function() {
                    form.submit();
                });
            });
        })
    </script>
{% endblock %}